import Head from "next/head";
import Image from "next/image";
import { Footer, Navbar } from "../../components";
import styles from "../../styles/Home.module.css";

const Events = () => {
  return (
    <>
      <Head>
        <title>CPMC EVENTS</title>
        <meta name="CPMC-EVENTS" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="font-Paytone text-[#fff] flex items-center flex-col gap-10 justify-center w-[100vw] h-[90vh]">
        <div className=" flex items-center flex-col shadow-cde px-[100px] py-[100px]">
          <h1 className="text-[50px]">
            Looking for <span className="text-[#f32053]"> Events</span> ?
          </h1>
          <h1 className="text-[30px]">
            We are planning some{" "}
            <span className="text-[#f32053]">Surprises</span> for you.
          </h1>
          <h1 className="text-[30px]">
            Stay <span className="text-[#f32053]">Tuned !</span>
          </h1>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default Events;
