import Head from "next/head";

import {
  LandingSlide,
  Timeline,
  Mission,
  Footer,
  Registers,
  JoinClub,
  AboutTeam,
  Questions,
  ClubOperations,
} from "../components";

export default function Home() {
  return (
    <>
      <Head>
        <title>CPMC DYPCOE</title>
        <meta name="CPMC-DYPCOE" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LandingSlide />
      <Timeline />
      <Mission />
      <ClubOperations />
      <JoinClub />
      <Registers />
      <AboutTeam />
      <Questions />
      <Footer />
    </>
  );
}
